version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=playlistgendb
      - POSTGRES_USER=master
      - POSTGRES_PASSWORD=flowers
    volumes:
      - pgdata:/var/lib/postgresql/data/
  web:
    container_name: playlist_generator
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - secrets.env
    depends_on:
      - db

volumes:
  pgdata:
